# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train_old.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val_ACC"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN"
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 5  # Number of parallel jobs


  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///${.study_name}.db

    # name of the study to persist optimization results
    study_name:  ${datamodule.dataset_name}_${model.name}_${size}${suffix}

    # number of parallel workers
#    n_jobs: 5

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 2000

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42

    # define hyperparameter search space
    params:
      model.beta: choice(0.001, 0.01, 0.1, 1, 10)
      model.entropy_coef: choice(0, 1)
      model.reconstruction_coef: choice(0, 0.001, 0.01, 0.1, 1, 10)
      model.triplet_loss_coef: choice(0, 0.001, 0.01, 0.1, 1, 10)
      model.triplet_threshold: choice(0.7, 0.8, 0.9)
      model.timeseries_encoder.encoding_size: choice(16, 32, 64, 128)