# metrics to present on hparams table used for test results

metrics:
  val_loss: 0
  val_ACC: 0
  val_BALACC: 0
  val_RECALL: 0
  val_PRECISION: 0
  val_AUROC: 0
  val_AUPRC: 0
  test_loss: 0
  test_ACC: 0
  test_BALACC: 0
  test_RECALL: 0
  test_PRECISION: 0
  test_AUROC: 0
  test_AUPRC: 0
  optimize_val_AUROC: 0

optimize: val_AUROC
