defaults:
  - _self_
  - datamodule: tsc/ssl_uea
  - model: tsc/ss_gpvib_e_inception_d_flatten
  - trainer: gpu
  - logger: wandb
  - callbacks: default
  - hydra: default
  - debug:
  - paths: default
  - hparams_search: tsc/ss_gp_vib
  - metrics: tsc
  - extras: default

seed: 42
mode: experiment
run_test: true
optimized_metric: ${metrics.optimize}

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
ckpt_path: null # path to checkpoint model


# name of the run, should be used along with experiment mode
datamodule_name: uea
model_name: ${model.name}
num_runs: 1
size: ssl_40
num_labeled: 0.4

