defaults:
  - _self_
  - datamodule: hmnist/ss_hmnist
  - model: hmnist/ss_gpvib_e_cnn1d_dl_flatten
  - trainer: gpu
  - logger: tensorboard
  - callbacks: default
  - hydra: default
  - debug:
  - paths: default
  - metrics: vib_eval
  - extras: default

seed:
mode: eval

ckpt_path:

# name of the run, should be used along with experiment mode
datamodule_name: ss_hmnist
model_name: ss_gpvib_e_cnn1d_dl_flatten
size: ssl_0.5


