defaults:
  - _self_
  - datamodule:
  - model:
  - trainer: gpu
  - logger: tensorboard
  - callbacks: default
  - hydra: default
  - debug:
  - paths: default
  - metrics: default
  - extras: default

seed:
mode: eval

ckpt_path:

# name of the run, should be used along with experiment mode
datamodule_name:
model_name: ${model.name}
size:
num_labeled:


