defaults:
  - _self_
  - datamodule:
  - model: hmnist/ss_gpvib_e_cnn1d_dl_flatten
  - trainer: gpu2
  - logger: wandb
  - callbacks: hmnist
  - hydra: default
  - debug:
  - paths: default
  - hparams_search:
  - metrics: vib_val
  - extras: default

seed: 42
mode: experiment
run_test: True
optimized_metric: ${metrics.optimize}

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
ckpt_path: null # path to checkpoint model

# name of the run, should be used along with experiment mode
datamodule_name: hmnist
model_name: ${model.name}
size:
num_labeled:


