defaults:
  - _self_
  - datamodule: ss_tsc
  - model: tsc/ss_gpvib_e_inception_d_flatten
  - trainer: gpu
  - logger: wandb
  - callbacks: default
  - hydra: default
  - debug:
  - paths: default
#  - hparams_search: hmnist/ss_gpvib_e_cnn1d_dl_flatten
  - metrics: tsc
  - extras: default

seed: 42
mode: debug
run_test: False
optimized_metric: ${metrics.optimize}

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
ckpt_path: null # path to checkpoint model

# name of the run, should be used along with experiment mode
datamodule_name: tsc
model_name: ss_gpvib_e_cnn1d_dl_flatten


