name: ss_gp-vae_inception
_target_: src.models.variational.ss_gp_vib.SemiSupervisedGPVIB
_partial_: True

defaults:
  - tsc_default.yaml

timeseries_encoder:
  _target_: src.models.encoders.InceptionEncoder
  _partial_: True
  input_n_channels: -1
  encoding_size: 128 # how many series in the lattent space
  encoding_series_size: -1 # the length of each series in the latent space
  number_of_filters: 32 # there are 4 kernels so final channel size is 128
  bottleneck_size: ${model.timeseries_encoder.number_of_filters}
  use_bottleneck: true
  depth: 1


encoder:
  _target_: src.models.encoders.BandedJointEncoder
  _partial_: True
  precision_activation:
    _target_: torch.nn.Softmax
  encoding_size: ${model.timeseries_encoder.encoding_size}


decoder:
  _target_: src.models.decoders.FlattenMultinomialDecoder
  _partial_: True
  z_dim: ${model.timeseries_encoder.encoding_size}
  hidden_size_1: -1
  hidden_size_2: -1
  hidden_size_3: -1
  num_samples: ${model.num_samples}
  output_size: ${model.num_classes}


data_decoder:
  _target_: src.models.decoders.InceptionDecoder
  _partial_: True
  output_n_channels:
  number_of_filters: 32 # there are 4 kernels so final channel size is 128
  bottleneck_size: 32
  use_bottleneck: true
  encoded_n_channels: ${model.timeseries_encoder.encoding_size}
  encoded_series_size: ${model.timeseries_encoder.encoding_series_size}
  num_samples: ${model.num_samples}


is_vae: true
is_ssl: false
data_beta: 1
beta: 0
entropy_coef: 0
reconstruction_coef: 0