name: ss_gp-vib_inception
_target_: src.models.variational.ss_gp_vib.SemiSupervisedGPVIB
_partial_: True

defaults:
  - tsc_default.yaml

timeseries_encoder:
  _target_: src.models.encoders.InceptionEncoder
  _partial_: True
  input_n_channels: -1
  encoding_size: 128 # how many series in the latent space
  encoding_series_size: 10 # the length of each series in the latent space
  number_of_filters:  32 # there are 4 kernels
  bottleneck_size: 32
  use_bottleneck: true
  depth: 1


encoder:
  _target_: src.models.encoders.BandedJointEncoder
  _partial_: True
  precision_activation:
    _target_: torch.nn.Softmax
  encoding_size: ${model.timeseries_encoder.encoding_size}


decoder:
  _target_: src.models.decoders.FlattenMultinomialDecoder
  _partial_: True
  z_dim: ${model.timeseries_encoder.encoding_size}
  hidden_size_1: -1
  hidden_size_2: -1
  hidden_size_3: -1
  num_samples: ${model.num_samples}
  output_size:


data_decoder:
  _target_: src.models.decoders.InceptionDecoder
  _partial_: True
  output_n_channels:
  number_of_filters: ${model.timeseries_encoder.number_of_filters}
  bottleneck_size: ${model.timeseries_encoder.bottleneck_size}
  use_bottleneck: ${model.timeseries_encoder.use_bottleneck}
  encoded_n_channels: ${model.timeseries_encoder.encoding_size}
  encoded_series_size: ${model.timeseries_encoder.encoding_series_size}
  num_samples: ${model.num_samples}


is_vae: false
is_ssl: false
data_beta: 0
beta: 0.0001
entropy_coef: 0
reconstruction_coef: 0
triplet_loss_coef: 1
classification_coef: 10
triplet_threshold: 0.9
triplet_dist: jsd # euclidean