name: ss_gp-vib

_target_: src.models.variational.ss_gp_vib.SemiSupervisedGPVIB
_partial_: True

defaults:
  - tsc_default.yaml

timeseries_encoder:
  _target_: src.models.encoders.TimeSeriesDataEncoder2
  _partial_: True
  input_size: -1
  ts_embedding_size: -1
  n_cnn_layers: 2
  out_channels_1: 16
  out_channels_2: 16
  out_channels_3: -1
  out_channels_4: -1
  kernel_size_1: 5
  kernel_size_2: 3
  kernel_size_3: -1
  kernel_size_4: -1
  padding_1: 1
  padding_2: 0
  padding_3: -1
  padding_4: -1
  dropout_1: 0
  dropout_2: 0
  dropout_3: -1
  dropout_4: -1
  time_series_hidden_1: -1
  time_series_hidden_2: -1
  time_series_hidden_3: -1
  hidden_size_1: -1
  hidden_size_2: -1
  hidden_size_3: -1
  timeseries_size: 10
  encoding_size: 1


encoder:
  _target_: src.models.encoders.BandedJointEncoder
  _partial_: True
  precision_activation:
    _target_: torch.nn.Softmax
  encoding_size: ${model.timeseries_encoder.encoding_size}


decoder:
  _target_: src.models.decoders.FlattenMultinomialDecoder
  _partial_: True
  z_dim: ${model.timeseries_encoder.encoding_size}
  hidden_size_1: 128
  hidden_size_2: 32
  hidden_size_3: -1
  num_samples: ${model.num_samples}
  output_size: ${model.num_classes}


data_decoder:
  _target_: src.models.decoders.GaussianDataDecoder
  _partial_: True
  output_n_channels:
  output_length:
  latent_n_channels:
  latent_length:
  num_samples: ${model.num_samples}


is_vae: false
is_ssl: true
data_beta: 0
beta: 0.0001
entropy_coef: 0
reconstruction_coef: 0.001
triplet_loss_coef: 0
classification_coef: 1
triplet_threshold: 0.9
triplet_dist: euclidean # jsd