_target_: src.datasets.tsc.ss_tsc.SemiSupervisedTSC
_partial_: true

download_dir: C:\Developments\GP-VIB\data\tsc\ucr #${paths.data_dir}/tsc/ucr
download_url: https://www.timeseriesclassification.com/aeon-toolkit/Archives/Univariate2018_ts.zip
file_name: Univariate2018_ts.zip
batch_size: 64
num_workers: 1
num_labeled: 0.4
num_val: 0 # ignore
dataset_name: Yoga
cross_val_split_index: 0
is_data_missing: False
validation_split_seed: 42
is_ssl: True