_target_: src.datasets.tsc.ss_tsc.SemiSupervisedTSC
_partial_: true

download_dir: ${paths.data_dir}/tsc/uea
download_url: https://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip
file_name: Multivariate2018_ts.zip
batch_size: 64
num_workers: 1
num_labeled: ${num_labeled}
num_val: 0 # ignore
dataset_name: PEMS-SF
cross_val_split_index: 0
is_data_missing: False
validation_split_seed: 42
is_ssl: ${model.is_ssl}
